[project]
name = "fakenews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=5.0.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
